version: "3"
services:
  api:
    environment:
      - MONGO_FLASK=d_user:distribuidos20192
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
    - .:/app
    ports:
      - "4000:80"

  healthweb:
    build:
      context: ./healthweb
      dockerfile: Dockerfile
    volumes:
    - .:/app
    ports:
      - "5000:80"